version: '3'
services:
  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  communication:
    image: mattmagin/node-sonos-http-api
    network_mode: host # Changed from networks: my_network
    environment:
      - NODE_ENV=production
      - PORT=${COMMUNICATION_PORT}
  rails:
    build: .
    volumes:
      - "./:/var/www"
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - RAILS_ENV=development
    depends_on:
      - db
      - communication